[package]
name = "rust-comp-syntax-to-middle"
version = "0.1.0"
authors = ["Chris Gregory <czipperz@gmail.com>"]
edition = "2018"

[dependencies]
rust-comp-syntax = { path = "../rust-comp-syntax" }
rust-comp-middle = { path = "../rust-comp-middle" }
