#!/bin/sh

if [ "$(git diff --name-only | wc -l)" != 0 ]; then
    echo >&2
    echo "ERROR: Stash changes before committing" >&2
    exit 1
fi

# auto format changed sources then add the formatting to the stage
cargo fmt --all
git add $(git diff --name-only --staged)

if ! RUST_BACKTRACE=1 cargo test --all -q; then
    echo >&2
    echo "ERROR: Tests are failing" >&2
    exit 1
fi
