[package]
name = "rust-comp-run"
version = "0.1.0"
authors = ["Chris Gregory <czipperz@gmail.com>"]
edition = "2018"

[dependencies]
rust-comp-diagnostic = { path = "../rust-comp-diagnostic" }
rust-comp-front = { path = "../rust-comp-front" }
rust-comp-opt = { path = "../rust-comp-opt" }
